# Generated by Django 3.2.2 on 2021-05-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='gallery/')),
                ('caption', models.TextField()),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('boys', 'Boys'), ('girls', 'Girls')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
