# Generated by Django 3.2.2 on 2021-05-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('men', 'Men designs'), ('women', 'Ladies designs'), ('boys', 'Boys'), ('girls', 'Girls')], max_length=10)),
                ('picture', models.ImageField(upload_to='products/')),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
